version: "3.7"
services:
  api:
    container_name: phonebook_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api/src:/app/src"
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${API_HOST}
      - PORT=${API_PORT}
      - VERSION=${API_VERSION}
      - DB_URL=${DB_URL}
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - db
    depends_on:
      - db

  web:
    container_name: phonebook_web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        HOST: ${WEB_HOST}
        PORT: ${WEB_PORT}
        API_HOST: ${API_HOST}
        API_PORT: ${API_PORT}
        API_VERSION: ${API_VERSION}
    volumes:
      - "./web/src:/app/src"
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${WEB_HOST}
      - PORT=${WEB_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    links:
      - api
    depends_on:
      - api

  db:
    container_name: phonebook_db
    image: mongo:latest
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
    - type: "volume"
      source: db-data
      target: /data/db
      volume:
        nocopy: true
    command: mongod --port ${DB_PORT}

volumes:
  db-data:
